# Generated by Django 4.2 on 2023-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('quant_min', models.IntegerField(blank=True, null=True)),
                ('quant_disponivel', models.IntegerField(blank=True, null=True)),
                ('cod_barras', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
