# Generated by Django 4.2 on 2023-05-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_material_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateTimeField()),
                ('quant_entrada', models.IntegerField()),
                ('dataValidade', models.DateField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.material')),
            ],
        ),
    ]
