# Generated by Django 4.2 on 2023-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_estadopedido_pessoa_contacto_pessoa_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_fornecedor',
            name='contacto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contacto_pessoa',
            name='contacto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='acesso',
            field=models.IntegerField(),
        ),
    ]
