# Generated by Django 4.2 on 2023-05-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='apelido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
