# Generated by Django 4.2 on 2023-05-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dadosuser_rename_contacto_pessoa_contacto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosuser',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cargo'),
        ),
        migrations.AlterField(
            model_name='dadosuser',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contacto_user'),
        ),
    ]
